### ISSUE TITLE
【开发环境】跳转无效

### ISSUE THREAD

**Issue by Miguitian** [TencentBlueKing/bk-itsm#1102]
itsm：v2.6.2
按照官网的部署开发环境的手册进行部署https://github.com/TencentBlueKing/bk-itsm/blob/master/docs/install/dev_deploy.md。 本地服务启动成功，在登陆的时候跳转到了paas的登陆界面，但是在输入完账号密码之后，并没有跳转到开发环境的itsm界面,请问是哪里配置不对或者少配置了东西
![image](https://github.com/TencentBlueKing/bk-itsm/assets/81501401/809b5f8a-1d2c-4fdf-a75b-1f40d7cc5cf2)
跳转无效的截图，输入正确密码后却没有进行跳转

![image](https://github.com/TencentBlueKing/bk-itsm/assets/81501401/4cf6292c-4719-46c9-a4ed-12b6480a5d50)
后台服务日志，一直显示302状态

**Comment by Miguitian** [comment]
@hanshuaikang

**Comment by hanshuaikang** [comment]
> 

其他的日志信息有吗

**Comment by Miguitian** [comment]
> > 
> 
> 其他的日志信息有吗

目前没有，连接的是其他环境的社区版的paas平台，本地启动的只有一个itsm
然后在paas平台上我只在功能测试白名单中添加了我的APP_ID 也就是bk-itsm-dev. 其他并没有做任何操作，在paas平台上我是否少做了哪些配置

**Comment by hanshuaikang** [comment]
> 

这个要看下登陆成功之后bk_token 是否写入了cookie 。 BK_PAAS_HOST这些环境变量是否配置？ blueapps.account.components.bk_token.middlewares.LoginRequiredMiddleware.authenticate

**Comment by Miguitian** [comment]
> BK_PAAS_HOST

![image](https://github.com/TencentBlueKing/bk-itsm/assets/81501401/ed192ac5-e5c2-4f9d-9edf-96c555409bc8)
环境变量是有设置的，另外因为启动时总是报iam的错误，所以多设置了一个环境变量。USE_IAM=false。
目前在登陆成功后，就没有任何反应了，您说的这个查看cookie的方法我可以一会试着找一下，您看下我设置的环境变量有无问题，本地host的我也设置了。然后我也想请教一下，在paas平台上是否还需要做什么配置或者操作？正常情况下是否是本地配置好环境变量，然后启动程序，通过浏览器访问程序，自动跳转登陆页面，然后输入账号密码后就跳转到本地的itsm环境

**Comment by liugy1028** [comment]
大佬， 你是怎么解决的，我也是这个问题，登录后跳回来index了， 但是init 又报401 的鉴权
