### ISSUE TITLE
【平台管理——单据状态】已经删除的自定义单据状态未清除

### ISSUE THREAD

**Issue by pagezz-canway** [TencentBlueKing/bk-itsm#1137]
版本：2.6.5
分类：缺陷
![BUG](https://github.com/TencentBlueKing/bk-itsm/assets/8849151/827417ff-be85-4c7b-b1ab-d1f58b248f64)

**Comment by hanshuaikang** [comment]
@luofann 前端删除单据状态成功时，未删除列表中的元素
