### ISSUE TITLE
【平台管理——单据状态】自定义状态设置不生效

### ISSUE THREAD

**Issue by pagezz-canway** [TencentBlueKing/bk-itsm#1138]
版本：2.6.5
分类：缺陷
复现步骤：
![image](https://github.com/TencentBlueKing/bk-itsm/assets/8849151/f9b10a49-1eb5-4190-9291-f9e6ea625e21)
![image](https://github.com/TencentBlueKing/bk-itsm/assets/8849151/b15b6485-bd00-4473-8f12-3112344bed16)
![image](https://github.com/TencentBlueKing/bk-itsm/assets/8849151/b8f8edac-b978-47e3-a9d0-8f8d13321510)
![image](https://github.com/TencentBlueKing/bk-itsm/assets/8849151/1fb6f9bd-ba19-455d-aae8-947d11b9c9b7)
![image](https://github.com/TencentBlueKing/bk-itsm/assets/8849151/7bc68736-1fab-47aa-b863-cd7b8d263ebe)

**Comment by hanshuaikang** [comment]
已修复
