### ISSUE TITLE
【平台管理——优先级】数据字典文案无对应功能

### ISSUE THREAD

**Issue by pagezz-canway** [TencentBlueKing/bk-itsm#1140]
版本：2.6.5
分类：缺陷
![image](https://github.com/TencentBlueKing/bk-itsm/assets/8849151/b08265bb-2a0d-409d-9508-9648d374f139)

**Comment by hanshuaikang** [comment]
数据字典在某个版本评审中被砍掉了，只保留了一个入口去修改配置
