### ISSUE TITLE
itsm暴露remark api 

### ISSUE THREAD

**Issue by liuliancao** [TencentBlueKing/bk-itsm#1164]
目前webhook结束以后，希望能够自动评论下这个 /api/ticket/remark/我怎么从蓝鲸平台调用呢？是否可以暴露出来？

**Comment by hanshuaikang** [comment]
评论单据的api是有的，esb应该没有，但是最新版网关是有的

**Comment by liuliancao** [comment]
不升级 就只能直接调用docker容器了是吧
