### ISSUE TITLE
请问有Pipline流程引擎的说明文档吗

### ISSUE THREAD

**Issue by iAmBrid** [TencentBlueKing/bk-itsm#1207]
数据流向图中有提到Pipeline流程引擎有其他的说明文档，但是在GitHub中没有找到，请问可以提供一下吗？
![image](https://github.com/TencentBlueKing/bk-itsm/assets/32071476/f8954e37-7d61-40eb-aa65-85ab2575bf22)

**Comment by hanshuaikang** [comment]
https://github.com/TencentBlueKing/bamboo-engine
