### ISSUE TITLE
dev环境有没有详细的教程

### ISSUE THREAD

**Issue by lvhaoran88** [TencentBlueKing/bk-itsm#130]
按照官网给的开发环境搭建，一点也跑不起来。还有好多包都变名字了，能不能更新一下。dev环境的依赖能不能说清楚一点。都摸索3天了。还是摸索不出来。建议给个从0开始搭建环境的教程

**Comment by hanshuaikang** [comment]
这部分的文档我们尽快完善

**Comment by hanshuaikang** [comment]
具体遇到了哪些问题可以贴出来我们看下

**Comment by lvhaoran88** [comment]
> 具体遇到了哪些问题可以贴出来我们看下

已经解决了。有5 6处需要修改的地方。抽空我把需要修改的地方补充上去。我怎么提交需要附上的内容呢，有相关操作手册吗

**Comment by hanshuaikang** [comment]
> > 具体遇到了哪些问题可以贴出来我们看下
> 
> 已经解决了。有5 6处需要修改的地方。抽空我把需要修改的地方补充上去。我怎么提交需要附上的内容呢，有相关操作手册吗

欢迎给我们提交 PR， 我们评估过之后，会合并到我们的代码文档中， 你可以先fork我们的代码在你的仓库，提PR到我们的开发分支，v2.6.0_develop ，详细步骤可以查看项目wiki

**Comment by hanshuaikang** [comment]
看了一下代码，关于数据库，本地请使用dev模式，并且使用local_settings.py方式配置，这些改动会导致itsm线上环境不可用的, 这些文件在本地是不会被加载到的，pr我就先close了，未来我们会完善本地的安装文档。感谢您的反馈。
