### ISSUE TITLE
itsm 创建工单API

### ISSUE THREAD

**Issue by mingyueqingfeng10** [TencentBlueKing/bk-itsm#1307]
请问itsm创建工单api这个参数是什么 怎么传 能否通过这个api来自动创建工单（比如说zabbix告警通过调用此api来自动创建工单，不同告警接收人不一样 那创建工单的时候审批人能不能动态呢 我传参来指定）
![--714eefda89627536cbd333d82305d9a8](https://github.com/TencentBlueKing/bk-itsm/assets/84175872/cfeda6ea-0c6d-4f68-a1c6-80242a1cbe8b)

**Comment by benero** [comment]
你好，可以使用此API 创建工单：https://bk.tencent.com/docs/markdown/ZH/ITSM/2.6/APIDocs/itsm/zh-hans/create_ticket.md
1. meta.state_processors：是在单据流转后为指定节点预定义处理人，格式为：$state_id: "人员列表"
2. 按你提及的场景，建议在【表单】新增审批人，之后在【审批节点】引用此字段处理
<img width="956" alt="image" src="https://github.com/TencentBlueKing/bk-itsm/assets/897663/1dc9c85d-db65-459f-9131-bac3e0d55e9c">
