### ISSUE TITLE
执行migrate失败mistune.Markdown()

### ISSUE THREAD

**Issue by zhangle231** [TencentBlueKing/bk-itsm#1308]
File "D:\project\蓝鲸\src\bk-itsm\itsm\iadmin\models.py", line 247, in init_version_log_info
    mk = mistune.Markdown()
TypeError: __init__() missing 1 required positional argument: 'renderer'

mistune==2.0.5

**Comment by benero** [comment]
thx， fixed: https://github.com/TencentBlueKing/bk-itsm/pull/1312
