### ISSUE TITLE
权限中心自定义和用户组审批报错缺少自定义字段

### ISSUE THREAD

**Issue by lTimej** [TencentBlueKing/bk-itsm#1381]
<img width="995" alt="image" src="https://github.com/user-attachments/assets/9812dbbe-af3c-45fb-848d-db4ac54b324d">

<img width="741" alt="image" src="https://github.com/user-attachments/assets/460fd0ca-828f-44e3-b727-73fb696e7f3e">

问题描述：
这里如果新添增一些字段，权限中心发起审批的时候就会报错说这些字段没有传，然后把这个新增字段删了之后去申请权限还是报字段必传错误

**Comment by benero** [comment]
审批流程修改需要在最后一次提交后，才会更新服务信息
