### ISSUE TITLE
我在使用ITSM2.5.9遇到了很多问题

### ISSUE THREAD

**Issue by wangxi-yunjisuan** [TencentBlueKing/bk-itsm#366]
1.在使用2.5.9时，我们在之前2.5.2的版本，自动化工单升级以后出现了问题，之前嵌入的标准运维流程已经无法打开。
![image](https://user-images.githubusercontent.com/52589521/149703609-db6aaa33-d4cd-40c3-82d1-b891b12d188d.png)

2.在使用2.5.9使用的时候如何向标准运维进行传参输出，之前是可选框进行选择，但是更新2.5.9以后无法使用下拉框选择，变成了填写变量，请问我该何如才能解决，
![image](https://user-images.githubusercontent.com/52589521/149703783-aac907c6-1839-43df-b7f3-6cf8c3f25a21.png)

以上两个问题我从2021-11-09 10:18:20就已经在蓝鲸论坛上发帖请求帮助，但是至今都没有人帮助我。

**Comment by hanshuaikang** [comment]
麻烦你把f12我们看下，请问是企业版吗

**Comment by hanshuaikang** [comment]
2.5.2 直接升级到2.5.9 吗
