### ISSUE TITLE
2.5.9.xxx可以直接升级到2.6.0.x吗？

### ISSUE THREAD

**Issue by lvhaoran88** [TencentBlueKing/bk-itsm#374]
蓝鲸开源版6.0.5版本
bk_itsm: 3.5.9.xxx
我想build 2.6.x，build完之后可以直接在2.5.9.xxx基础上进行升级吗？我之前的数据会不会受影响

**Comment by hanshuaikang** [comment]
2.5.9 包含自动过单的版本吗？

**Comment by lvhaoran88** [comment]
不太清楚，我用的是S-mart市场上的安装包具体版本号为 2.5.9.336，麻烦您这边确认一下。我找不到更高的2.5.9.xxx的版本了

**Comment by lampardtang** [comment]
> 不太清楚，我用的是S-mart市场上的安装包具体版本号为 2.5.9.336，麻烦您这边确认一下。我找不到更高的2.5.9.xxx的版本了

s-mart上已经上线最新的2.6.0版本了，可以直接更新

**Comment by hanshuaikang** [comment]
> > 不太清楚，我用的是S-mart市场上的安装包具体版本号为 2.5.9.336，麻烦您这边确认一下。我找不到更高的2.5.9.xxx的版本了
> 
> s-mart上已经上线最新的2.6.0版本了，可以直接更新

好的，有问题欢迎给我们提issues or pr
