### ISSUE TITLE
ITSM缺乏移动端功能

### ISSUE THREAD

**Issue by yeguangfang** [TencentBlueKing/bk-itsm#391]
ITSM目前缺乏移动端审批功能，希望能够通过h5接入企业内部的移动安全门户。

**Comment by hanshuaikang** [comment]
移动端目前正在讨论通用方案，后续方案出来之后会尽快支持。目前我移动端只支持微信接入，

**Comment by hanshuaikang** [comment]
https://github.com/TencentBlueKing/bk-itsm/blob/v2.6.x_develop/docs/install/qy_weixin_config.md
