### ISSUE TITLE
ITSM权限中心注册

### ISSUE THREAD

**Issue by SmallJune** [TencentBlueKing/bk-itsm#563]
通过do_migrate.py 引入源码当中的inital.json
能看到注册的项目
当配置全新存在报错
![image](https://user-images.githubusercontent.com/8952270/161217051-b102f82b-1fdc-4e83-a8ee-d929c23fab27.png)
![image](https://user-images.githubusercontent.com/8952270/161216081-cb21cb7b-89c4-4d38-a22e-47ce4e0f2164.png)
![image](https://user-images.githubusercontent.com/8952270/161215432-2060aae0-74cc-4fb6-9f3a-2c69b96de089.png)

**Comment by hanshuaikang** [comment]
"provider_config": {
      "host": "",
      "auth": "basic"
  }

host要填成你saas的地址
