### ISSUE TITLE
后台运营数据错误

### ISSUE THREAD

**Issue by Foustdg** [TencentBlueKing/bk-itsm#587]
版本号 V2.5.8 
![image](https://user-images.githubusercontent.com/20092889/162871573-fe2f0b5d-effd-45e2-9553-4b63686e3e6f.png)
运营数据 上周数据都是 0，调用接口 /o/bk_itsm/api/ticket/operational/compared_same_week/
接口返回值
{"result":true,"code":"OK","message":"success","data":{"ticket":{"this_week_count":3,"last_week_count":0,"ratio":"300.0%"},"service":{"this_week_count":0,"last_week_count":0,"ratio":"0.0%"},"biz":{"this_week_count":2,"last_week_count":0,"ratio":"200.0%"},"user":{"this_week_count":9,"last_week_count":0,"ratio":"900.0%"}}}

**Comment by hanshuaikang** [comment]
好的，这个我们排查下
