### ISSUE TITLE
关于触发器无法重复执行的问题

### ISSUE THREAD

**Issue by SmallJune** [TencentBlueKing/bk-itsm#599]
def check_and_create(self, source_type, source_id, action, rule):
            action_count = Action.objects.filter(
                signal=self.trigger.signal,
                sender=self.trigger.sender,
                source_type=source_type,
                source_id=source_id,
                schema_id=action.id,
                rule_id=rule.id,
                trigger_id=self.trigger.id,
            ).count()
            logger.info(
                "[check_and_create] source_type={}, source_id={}. action={}, rule={}, action_count={}".format(
                    source_type, source_id, action.id, rule.id, action_count
                )
            )
            if action_count == 0: 
//. 该代码的意思是已创建的触发器就不在创建，是否有逻辑问题， 如果再次进去循环的，触发器就不应该执行嘛？
                obj = Action.objects.create(
                    signal=self.trigger.signal,
                    sender=self.trigger.sender,
                    context=self.context,
                    source_type=source_type,
                    source_id=source_id,
                    schema_id=action.id,
                    rule_id=rule.id,
                    trigger_id=self.trigger.id,
                )
                return obj
© 2022 GitHub, Inc.
[Terms](https://docs.github.com/en/github/site-policy/github-terms-of-service)
[Privacy](https://docs.github.com/en/github/site-policy/github-privacy-statement)

**Comment by hanshuaikang** [comment]
请问版本是？

**Comment by SmallJune** [comment]
所有版本都存在这个问题

**Comment by hanshuaikang** [comment]
这个我们近期排查修复一下

**Comment by SmallJune** [comment]
好的
如有更改，请及时通知

**Comment by hanshuaikang** [comment]
好的

**Comment by hanshuaikang** [comment]
2.6.1 版本会支持
