### ISSUE TITLE
ITSM 能否支持标准运维节点输出参数作为下个节点的输入参数

### ISSUE THREAD

**Issue by xiaoge888168** [TencentBlueKing/bk-itsm#635]
![image](https://user-images.githubusercontent.com/39146216/165049569-9da5d51e-7b01-437e-8162-ca8fdd2891b2.png)

**Comment by hanshuaikang** [comment]
已排期

**Comment by hanshuaikang** [comment]
目前标准运维的接口并未返回相关的输出参数，这个需要等待标准运维相关接口支持后才可以
