### ISSUE TITLE
前端 index-dev.html 值获取不到

### ISSUE THREAD

**Issue by yufuxiao** [TencentBlueKing/bk-itsm#812]
修改成具体的变量后：

![image](https://user-images.githubusercontent.com/33924014/177128976-46a28cff-ca7c-4eb2-b1c8-277d8908e03f.png)

前端页面：
![image](https://user-images.githubusercontent.com/33924014/177129162-7eda5fa7-fab6-48f0-82c0-f38b1dd1fe5c.png)

**Comment by hanshuaikang** [comment]
重新编译了吗

**Comment by yufuxiao** [comment]
请继续帮忙看下这个问题




她°
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TencentBlueKing/bk-itsm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月4日(星期一) 晚上6:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TencentBlueKing/bk-itsm] 前端 index-dev.html 值获取不到 (Issue #812)





 
重新编译了吗

**Comment by luofann** [comment]
本地开发环境不会经过后台模板编译，调试的话直接写死固定的值就好

**Comment by yufuxiao** [comment]
好 明白了&nbsp; 谢谢
另外想问一个问题，用户管理我想针对部门做一些字段的增加 这个有什么办法吗




她°
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TencentBlueKing/bk-itsm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月5日(星期二) 上午10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TencentBlueKing/bk-itsm] 前端 index-dev.html 值获取不到 (Issue #812)





 
本地开发环境不会经过后台模板编译，调试的话直接写死固定的值就好

**Comment by hanshuaikang** [comment]
这个要联系用户管理相关的开发者

**Comment by yufuxiao** [comment]
好 谢谢，我问题解决了




她°
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TencentBlueKing/bk-itsm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月5日(星期二) 上午10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TencentBlueKing/bk-itsm] 前端 index-dev.html 值获取不到 (Issue #812)





 
这个要联系用户管理相关的开发者

**Comment by yufuxiao** [comment]
帮忙看下 github 上面的问题，
部署的时候提示：






她°
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TencentBlueKing/bk-itsm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月5日(星期二) 上午10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TencentBlueKing/bk-itsm] 前端 index-dev.html 值获取不到 (Issue #812)





 
这个要联系用户管理相关的开发者

**Comment by yufuxiao** [comment]
您好&nbsp; 帮忙看一下 github 上面问题




她°
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TencentBlueKing/bk-itsm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月5日(星期二) 上午10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TencentBlueKing/bk-itsm] 前端 index-dev.html 值获取不到 (Issue #812)





 
这个要联系用户管理相关的开发者
