### ISSUE TITLE
如何本地部署bk-itsm

### ISSUE THREAD

**Issue by Harry-Fang** [TencentBlueKing/bk-itsm#89]
本地部署itsm的时候报错，执行 
`pip install -r requirements.dev.txt` 
环境是ubuntu 20.04 LTS
pip 21.2.4 from /home/node/Downloads/code/bk-itsm/py3venv/lib/python3.8/site-packages/pip (python 3.8)
Python 3.8.10
[bk_itsm_error.log](https://github.com/TencentBlueKing/bk-itsm/files/7248696/bk_itsm_error.log)

**Comment by hanshuaikang** [comment]
建议在python3.6.5的环境下部署
